services:
  postgres:
    image: postgres:17
    container_name: ledger-flow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ledger_flow
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
    ports:
      - "5432:5432"
    volumes:
      - ledger_flow_postgres_data:/var/lib/postgresql/data

volumes:
  ledger_flow_postgres_data: